name: Repo Stats

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  repo-stats:
    name: Fetch and archive repo stats
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@ff48771cbb4324c3b77490bbfc26d6a5f3831cdb
        with:
          repository: Yudaotor/lyrimuse
          ghtoken: ${{ secrets.GHRS_GITHUB_API_TOKEN }}
